// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nps_cal.proto
// Protobuf C++ Version: 6.32.0-dev

#ifndef nps_5fcal_2eproto_2epb_2eh
#define nps_5fcal_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_nps_5fcal_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_nps_5fcal_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_nps_5fcal_2eproto;
}  // extern "C"
namespace nps {
class CalculatorRequest;
struct CalculatorRequestDefaultTypeInternal;
extern CalculatorRequestDefaultTypeInternal _CalculatorRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CalculatorRequest_class_data_;
class CalculatorResponse;
struct CalculatorResponseDefaultTypeInternal;
extern CalculatorResponseDefaultTypeInternal _CalculatorResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CalculatorResponse_class_data_;
class CorpusInput;
struct CorpusInputDefaultTypeInternal;
extern CorpusInputDefaultTypeInternal _CorpusInput_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CorpusInput_class_data_;
class NormalInput;
struct NormalInputDefaultTypeInternal;
extern NormalInputDefaultTypeInternal _NormalInput_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull NormalInput_class_data_;
class PensionInput;
struct PensionInputDefaultTypeInternal;
extern PensionInputDefaultTypeInternal _PensionInput_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PensionInput_class_data_;
}  // namespace nps
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace nps {

// ===================================================================


// -------------------------------------------------------------------

class PensionInput final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nps.PensionInput) */ {
 public:
  inline PensionInput() : PensionInput(nullptr) {}
  ~PensionInput() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PensionInput* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PensionInput));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PensionInput(::google::protobuf::internal::ConstantInitialized);

  inline PensionInput(const PensionInput& from) : PensionInput(nullptr, from) {}
  inline PensionInput(PensionInput&& from) noexcept
      : PensionInput(nullptr, ::std::move(from)) {}
  inline PensionInput& operator=(const PensionInput& from) {
    CopyFrom(from);
    return *this;
  }
  inline PensionInput& operator=(PensionInput&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PensionInput& default_instance() {
    return *reinterpret_cast<const PensionInput*>(
        &_PensionInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PensionInput& a, PensionInput& b) { a.Swap(&b); }
  inline void Swap(PensionInput* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PensionInput* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PensionInput* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PensionInput>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PensionInput& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PensionInput& from) { PensionInput::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PensionInput* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "nps.PensionInput"; }

 protected:
  explicit PensionInput(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PensionInput(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PensionInput& from);
  PensionInput(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PensionInput&& from) noexcept
      : PensionInput(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFMLGMSAMNTALLCTDFieldNumber = 1,
  };
  // double FML_GMS_AMNT_ALLCTD = 1;
  void clear_fml_gms_amnt_allctd() ;
  double fml_gms_amnt_allctd() const;
  void set_fml_gms_amnt_allctd(double value);

  private:
  double _internal_fml_gms_amnt_allctd() const;
  void _internal_set_fml_gms_amnt_allctd(double value);

  public:
  // @@protoc_insertion_point(class_scope:nps.PensionInput)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PensionInput& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double fml_gms_amnt_allctd_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nps_5fcal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PensionInput_class_data_;
// -------------------------------------------------------------------

class NormalInput final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nps.NormalInput) */ {
 public:
  inline NormalInput() : NormalInput(nullptr) {}
  ~NormalInput() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NormalInput* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NormalInput));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NormalInput(::google::protobuf::internal::ConstantInitialized);

  inline NormalInput(const NormalInput& from) : NormalInput(nullptr, from) {}
  inline NormalInput(NormalInput&& from) noexcept
      : NormalInput(nullptr, ::std::move(from)) {}
  inline NormalInput& operator=(const NormalInput& from) {
    CopyFrom(from);
    return *this;
  }
  inline NormalInput& operator=(NormalInput&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NormalInput& default_instance() {
    return *reinterpret_cast<const NormalInput*>(
        &_NormalInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(NormalInput& a, NormalInput& b) { a.Swap(&b); }
  inline void Swap(NormalInput* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NormalInput* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NormalInput* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NormalInput>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NormalInput& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NormalInput& from) { NormalInput::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NormalInput* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "nps.NormalInput"; }

 protected:
  explicit NormalInput(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  NormalInput(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NormalInput& from);
  NormalInput(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, NormalInput&& from) noexcept
      : NormalInput(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFMLTRNSCTNAMTFieldNumber = 1,
  };
  // double FML_TRNSCTN_AMT = 1;
  void clear_fml_trnsctn_amt() ;
  double fml_trnsctn_amt() const;
  void set_fml_trnsctn_amt(double value);

  private:
  double _internal_fml_trnsctn_amt() const;
  void _internal_set_fml_trnsctn_amt(double value);

  public:
  // @@protoc_insertion_point(class_scope:nps.NormalInput)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const NormalInput& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double fml_trnsctn_amt_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nps_5fcal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull NormalInput_class_data_;
// -------------------------------------------------------------------

class CorpusInput final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nps.CorpusInput) */ {
 public:
  inline CorpusInput() : CorpusInput(nullptr) {}
  ~CorpusInput() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CorpusInput* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CorpusInput));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CorpusInput(::google::protobuf::internal::ConstantInitialized);

  inline CorpusInput(const CorpusInput& from) : CorpusInput(nullptr, from) {}
  inline CorpusInput(CorpusInput&& from) noexcept
      : CorpusInput(nullptr, ::std::move(from)) {}
  inline CorpusInput& operator=(const CorpusInput& from) {
    CopyFrom(from);
    return *this;
  }
  inline CorpusInput& operator=(CorpusInput&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CorpusInput& default_instance() {
    return *reinterpret_cast<const CorpusInput*>(
        &_CorpusInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CorpusInput& a, CorpusInput& b) { a.Swap(&b); }
  inline void Swap(CorpusInput* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CorpusInput* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CorpusInput* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CorpusInput>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CorpusInput& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CorpusInput& from) { CorpusInput::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CorpusInput* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "nps.CorpusInput"; }

 protected:
  explicit CorpusInput(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CorpusInput(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CorpusInput& from);
  CorpusInput(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CorpusInput&& from) noexcept
      : CorpusInput(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFMLCASHBALFieldNumber = 1,
  };
  // double FML_CASH_BAL = 1;
  void clear_fml_cash_bal() ;
  double fml_cash_bal() const;
  void set_fml_cash_bal(double value);

  private:
  double _internal_fml_cash_bal() const;
  void _internal_set_fml_cash_bal(double value);

  public:
  // @@protoc_insertion_point(class_scope:nps.CorpusInput)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CorpusInput& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double fml_cash_bal_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nps_5fcal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CorpusInput_class_data_;
// -------------------------------------------------------------------

class CalculatorResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nps.CalculatorResponse) */ {
 public:
  inline CalculatorResponse() : CalculatorResponse(nullptr) {}
  ~CalculatorResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CalculatorResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CalculatorResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CalculatorResponse(::google::protobuf::internal::ConstantInitialized);

  inline CalculatorResponse(const CalculatorResponse& from) : CalculatorResponse(nullptr, from) {}
  inline CalculatorResponse(CalculatorResponse&& from) noexcept
      : CalculatorResponse(nullptr, ::std::move(from)) {}
  inline CalculatorResponse& operator=(const CalculatorResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CalculatorResponse& operator=(CalculatorResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CalculatorResponse& default_instance() {
    return *reinterpret_cast<const CalculatorResponse*>(
        &_CalculatorResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(CalculatorResponse& a, CalculatorResponse& b) { a.Swap(&b); }
  inline void Swap(CalculatorResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CalculatorResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CalculatorResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CalculatorResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CalculatorResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CalculatorResponse& from) { CalculatorResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CalculatorResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "nps.CalculatorResponse"; }

 protected:
  explicit CalculatorResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CalculatorResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CalculatorResponse& from);
  CalculatorResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CalculatorResponse&& from) noexcept
      : CalculatorResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFMLGMSAMNTALLCTDFieldNumber = 2,
    kFMLCASHBALFieldNumber = 3,
    kFMLIDDLSTPRCFieldNumber = 4,
    kFMLORDAMTBLCKDFieldNumber = 5,
    kFMLORDNETVLFieldNumber = 6,
    kFMLCSBNTBLNCSFieldNumber = 7,
    kFMLFMLORDAMTBLCKDCOVSTATUSFieldNumber = 1,
  };
  // double FML_GMS_AMNT_ALLCTD = 2;
  void clear_fml_gms_amnt_allctd() ;
  double fml_gms_amnt_allctd() const;
  void set_fml_gms_amnt_allctd(double value);

  private:
  double _internal_fml_gms_amnt_allctd() const;
  void _internal_set_fml_gms_amnt_allctd(double value);

  public:
  // double FML_CASH_BAL = 3;
  void clear_fml_cash_bal() ;
  double fml_cash_bal() const;
  void set_fml_cash_bal(double value);

  private:
  double _internal_fml_cash_bal() const;
  void _internal_set_fml_cash_bal(double value);

  public:
  // double FML_IDD_LST_PRC = 4;
  void clear_fml_idd_lst_prc() ;
  double fml_idd_lst_prc() const;
  void set_fml_idd_lst_prc(double value);

  private:
  double _internal_fml_idd_lst_prc() const;
  void _internal_set_fml_idd_lst_prc(double value);

  public:
  // double FML_ORD_AMT_BLCKD = 5;
  void clear_fml_ord_amt_blckd() ;
  double fml_ord_amt_blckd() const;
  void set_fml_ord_amt_blckd(double value);

  private:
  double _internal_fml_ord_amt_blckd() const;
  void _internal_set_fml_ord_amt_blckd(double value);

  public:
  // double FML_ORD_NET_VL = 6;
  void clear_fml_ord_net_vl() ;
  double fml_ord_net_vl() const;
  void set_fml_ord_net_vl(double value);

  private:
  double _internal_fml_ord_net_vl() const;
  void _internal_set_fml_ord_net_vl(double value);

  public:
  // double FML_CSB_NT_BLNCS = 7;
  void clear_fml_csb_nt_blncs() ;
  double fml_csb_nt_blncs() const;
  void set_fml_csb_nt_blncs(double value);

  private:
  double _internal_fml_csb_nt_blncs() const;
  void _internal_set_fml_csb_nt_blncs(double value);

  public:
  // int32 FML_FML_ORD_AMT_BLCKDCOV_STATUS = 1;
  void clear_fml_fml_ord_amt_blckdcov_status() ;
  ::int32_t fml_fml_ord_amt_blckdcov_status() const;
  void set_fml_fml_ord_amt_blckdcov_status(::int32_t value);

  private:
  ::int32_t _internal_fml_fml_ord_amt_blckdcov_status() const;
  void _internal_set_fml_fml_ord_amt_blckdcov_status(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:nps.CalculatorResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CalculatorResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double fml_gms_amnt_allctd_;
    double fml_cash_bal_;
    double fml_idd_lst_prc_;
    double fml_ord_amt_blckd_;
    double fml_ord_net_vl_;
    double fml_csb_nt_blncs_;
    ::int32_t fml_fml_ord_amt_blckdcov_status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nps_5fcal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CalculatorResponse_class_data_;
// -------------------------------------------------------------------

class CalculatorRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nps.CalculatorRequest) */ {
 public:
  inline CalculatorRequest() : CalculatorRequest(nullptr) {}
  ~CalculatorRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CalculatorRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CalculatorRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CalculatorRequest(::google::protobuf::internal::ConstantInitialized);

  inline CalculatorRequest(const CalculatorRequest& from) : CalculatorRequest(nullptr, from) {}
  inline CalculatorRequest(CalculatorRequest&& from) noexcept
      : CalculatorRequest(nullptr, ::std::move(from)) {}
  inline CalculatorRequest& operator=(const CalculatorRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CalculatorRequest& operator=(CalculatorRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CalculatorRequest& default_instance() {
    return *reinterpret_cast<const CalculatorRequest*>(
        &_CalculatorRequest_default_instance_);
  }
  enum SpecificInputCase {
    kNormal = 11,
    kCorpus = 12,
    kPension = 13,
    SPECIFIC_INPUT_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(CalculatorRequest& a, CalculatorRequest& b) { a.Swap(&b); }
  inline void Swap(CalculatorRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CalculatorRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CalculatorRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CalculatorRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CalculatorRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CalculatorRequest& from) { CalculatorRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CalculatorRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "nps.CalculatorRequest"; }

 protected:
  explicit CalculatorRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CalculatorRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CalculatorRequest& from);
  CalculatorRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CalculatorRequest&& from) noexcept
      : CalculatorRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFMLMFGROWTHFLGFieldNumber = 9,
    kFMLMODPLCDFLGFieldNumber = 10,
    kFMLUSRIDFieldNumber = 14,
    kFMLMFFREMNTHFieldNumber = 1,
    kFMLINTERVALFieldNumber = 2,
    kFMLSSSNIDFieldNumber = 4,
    kFMLFROMPERIODFieldNumber = 3,
    kFMLOTRNSCTNQTYFieldNumber = 5,
    kFMLCOVERQTYFieldNumber = 6,
    kFMLIDDBSTBIDQTYFieldNumber = 7,
    kFMLOSTTDYSFieldNumber = 8,
    kNormalFieldNumber = 11,
    kCorpusFieldNumber = 12,
    kPensionFieldNumber = 13,
  };
  // string FML_MF_GROWTH_FLG = 9;
  void clear_fml_mf_growth_flg() ;
  const ::std::string& fml_mf_growth_flg() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_fml_mf_growth_flg(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_fml_mf_growth_flg();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_fml_mf_growth_flg();
  void set_allocated_fml_mf_growth_flg(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_fml_mf_growth_flg() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_fml_mf_growth_flg(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_fml_mf_growth_flg();

  public:
  // string FML_MOD_PLCD_FLG = 10;
  void clear_fml_mod_plcd_flg() ;
  const ::std::string& fml_mod_plcd_flg() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_fml_mod_plcd_flg(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_fml_mod_plcd_flg();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_fml_mod_plcd_flg();
  void set_allocated_fml_mod_plcd_flg(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_fml_mod_plcd_flg() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_fml_mod_plcd_flg(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_fml_mod_plcd_flg();

  public:
  // string FML_USR_ID = 14;
  void clear_fml_usr_id() ;
  const ::std::string& fml_usr_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_fml_usr_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_fml_usr_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_fml_usr_id();
  void set_allocated_fml_usr_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_fml_usr_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_fml_usr_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_fml_usr_id();

  public:
  // int32 FML_MF_FRE_MNTH = 1;
  void clear_fml_mf_fre_mnth() ;
  ::int32_t fml_mf_fre_mnth() const;
  void set_fml_mf_fre_mnth(::int32_t value);

  private:
  ::int32_t _internal_fml_mf_fre_mnth() const;
  void _internal_set_fml_mf_fre_mnth(::int32_t value);

  public:
  // int32 FML_INTERVAL = 2;
  void clear_fml_interval() ;
  ::int32_t fml_interval() const;
  void set_fml_interval(::int32_t value);

  private:
  ::int32_t _internal_fml_interval() const;
  void _internal_set_fml_interval(::int32_t value);

  public:
  // int64 FML_SSSN_ID = 4;
  void clear_fml_sssn_id() ;
  ::int64_t fml_sssn_id() const;
  void set_fml_sssn_id(::int64_t value);

  private:
  ::int64_t _internal_fml_sssn_id() const;
  void _internal_set_fml_sssn_id(::int64_t value);

  public:
  // int32 FML_FROM_PERIOD = 3;
  void clear_fml_from_period() ;
  ::int32_t fml_from_period() const;
  void set_fml_from_period(::int32_t value);

  private:
  ::int32_t _internal_fml_from_period() const;
  void _internal_set_fml_from_period(::int32_t value);

  public:
  // int32 FML_OTRNSCTN_QTY = 5;
  void clear_fml_otrnsctn_qty() ;
  ::int32_t fml_otrnsctn_qty() const;
  void set_fml_otrnsctn_qty(::int32_t value);

  private:
  ::int32_t _internal_fml_otrnsctn_qty() const;
  void _internal_set_fml_otrnsctn_qty(::int32_t value);

  public:
  // int32 FML_COVER_QTY = 6;
  void clear_fml_cover_qty() ;
  ::int32_t fml_cover_qty() const;
  void set_fml_cover_qty(::int32_t value);

  private:
  ::int32_t _internal_fml_cover_qty() const;
  void _internal_set_fml_cover_qty(::int32_t value);

  public:
  // int32 FML_IDD_BST_BID_QTY = 7;
  void clear_fml_idd_bst_bid_qty() ;
  ::int32_t fml_idd_bst_bid_qty() const;
  void set_fml_idd_bst_bid_qty(::int32_t value);

  private:
  ::int32_t _internal_fml_idd_bst_bid_qty() const;
  void _internal_set_fml_idd_bst_bid_qty(::int32_t value);

  public:
  // int32 FML_O_STT_DYS = 8;
  void clear_fml_o_stt_dys() ;
  ::int32_t fml_o_stt_dys() const;
  void set_fml_o_stt_dys(::int32_t value);

  private:
  ::int32_t _internal_fml_o_stt_dys() const;
  void _internal_set_fml_o_stt_dys(::int32_t value);

  public:
  // .nps.NormalInput normal = 11;
  bool has_normal() const;
  private:
  bool _internal_has_normal() const;

  public:
  void clear_normal() ;
  const ::nps::NormalInput& normal() const;
  [[nodiscard]] ::nps::NormalInput* PROTOBUF_NULLABLE release_normal();
  ::nps::NormalInput* PROTOBUF_NONNULL mutable_normal();
  void set_allocated_normal(::nps::NormalInput* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_normal(::nps::NormalInput* PROTOBUF_NULLABLE value);
  ::nps::NormalInput* PROTOBUF_NULLABLE unsafe_arena_release_normal();

  private:
  const ::nps::NormalInput& _internal_normal() const;
  ::nps::NormalInput* PROTOBUF_NONNULL _internal_mutable_normal();

  public:
  // .nps.CorpusInput corpus = 12;
  bool has_corpus() const;
  private:
  bool _internal_has_corpus() const;

  public:
  void clear_corpus() ;
  const ::nps::CorpusInput& corpus() const;
  [[nodiscard]] ::nps::CorpusInput* PROTOBUF_NULLABLE release_corpus();
  ::nps::CorpusInput* PROTOBUF_NONNULL mutable_corpus();
  void set_allocated_corpus(::nps::CorpusInput* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_corpus(::nps::CorpusInput* PROTOBUF_NULLABLE value);
  ::nps::CorpusInput* PROTOBUF_NULLABLE unsafe_arena_release_corpus();

  private:
  const ::nps::CorpusInput& _internal_corpus() const;
  ::nps::CorpusInput* PROTOBUF_NONNULL _internal_mutable_corpus();

  public:
  // .nps.PensionInput pension = 13;
  bool has_pension() const;
  private:
  bool _internal_has_pension() const;

  public:
  void clear_pension() ;
  const ::nps::PensionInput& pension() const;
  [[nodiscard]] ::nps::PensionInput* PROTOBUF_NULLABLE release_pension();
  ::nps::PensionInput* PROTOBUF_NONNULL mutable_pension();
  void set_allocated_pension(::nps::PensionInput* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_pension(::nps::PensionInput* PROTOBUF_NULLABLE value);
  ::nps::PensionInput* PROTOBUF_NULLABLE unsafe_arena_release_pension();

  private:
  const ::nps::PensionInput& _internal_pension() const;
  ::nps::PensionInput* PROTOBUF_NONNULL _internal_mutable_pension();

  public:
  void clear_specific_input();
  SpecificInputCase specific_input_case() const;
  // @@protoc_insertion_point(class_scope:nps.CalculatorRequest)
 private:
  class _Internal;
  void set_has_normal();
  void set_has_corpus();
  void set_has_pension();
  inline bool has_specific_input() const;
  inline void clear_has_specific_input();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 14,
                                   3, 81,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CalculatorRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr fml_mf_growth_flg_;
    ::google::protobuf::internal::ArenaStringPtr fml_mod_plcd_flg_;
    ::google::protobuf::internal::ArenaStringPtr fml_usr_id_;
    ::int32_t fml_mf_fre_mnth_;
    ::int32_t fml_interval_;
    ::int64_t fml_sssn_id_;
    ::int32_t fml_from_period_;
    ::int32_t fml_otrnsctn_qty_;
    ::int32_t fml_cover_qty_;
    ::int32_t fml_idd_bst_bid_qty_;
    ::int32_t fml_o_stt_dys_;
    union SpecificInputUnion {
      constexpr SpecificInputUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE normal_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE corpus_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE pension_;
    } specific_input_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nps_5fcal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CalculatorRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NormalInput

// double FML_TRNSCTN_AMT = 1;
inline void NormalInput::clear_fml_trnsctn_amt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_trnsctn_amt_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline double NormalInput::fml_trnsctn_amt() const {
  // @@protoc_insertion_point(field_get:nps.NormalInput.FML_TRNSCTN_AMT)
  return _internal_fml_trnsctn_amt();
}
inline void NormalInput::set_fml_trnsctn_amt(double value) {
  _internal_set_fml_trnsctn_amt(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:nps.NormalInput.FML_TRNSCTN_AMT)
}
inline double NormalInput::_internal_fml_trnsctn_amt() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_trnsctn_amt_;
}
inline void NormalInput::_internal_set_fml_trnsctn_amt(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_trnsctn_amt_ = value;
}

// -------------------------------------------------------------------

// CorpusInput

// double FML_CASH_BAL = 1;
inline void CorpusInput::clear_fml_cash_bal() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_cash_bal_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline double CorpusInput::fml_cash_bal() const {
  // @@protoc_insertion_point(field_get:nps.CorpusInput.FML_CASH_BAL)
  return _internal_fml_cash_bal();
}
inline void CorpusInput::set_fml_cash_bal(double value) {
  _internal_set_fml_cash_bal(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:nps.CorpusInput.FML_CASH_BAL)
}
inline double CorpusInput::_internal_fml_cash_bal() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_cash_bal_;
}
inline void CorpusInput::_internal_set_fml_cash_bal(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_cash_bal_ = value;
}

// -------------------------------------------------------------------

// PensionInput

// double FML_GMS_AMNT_ALLCTD = 1;
inline void PensionInput::clear_fml_gms_amnt_allctd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_gms_amnt_allctd_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline double PensionInput::fml_gms_amnt_allctd() const {
  // @@protoc_insertion_point(field_get:nps.PensionInput.FML_GMS_AMNT_ALLCTD)
  return _internal_fml_gms_amnt_allctd();
}
inline void PensionInput::set_fml_gms_amnt_allctd(double value) {
  _internal_set_fml_gms_amnt_allctd(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:nps.PensionInput.FML_GMS_AMNT_ALLCTD)
}
inline double PensionInput::_internal_fml_gms_amnt_allctd() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_gms_amnt_allctd_;
}
inline void PensionInput::_internal_set_fml_gms_amnt_allctd(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_gms_amnt_allctd_ = value;
}

// -------------------------------------------------------------------

// CalculatorRequest

// int32 FML_MF_FRE_MNTH = 1;
inline void CalculatorRequest::clear_fml_mf_fre_mnth() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_mf_fre_mnth_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008U;
}
inline ::int32_t CalculatorRequest::fml_mf_fre_mnth() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorRequest.FML_MF_FRE_MNTH)
  return _internal_fml_mf_fre_mnth();
}
inline void CalculatorRequest::set_fml_mf_fre_mnth(::int32_t value) {
  _internal_set_fml_mf_fre_mnth(value);
  _impl_._has_bits_[0] |= 0x00000008U;
  // @@protoc_insertion_point(field_set:nps.CalculatorRequest.FML_MF_FRE_MNTH)
}
inline ::int32_t CalculatorRequest::_internal_fml_mf_fre_mnth() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_mf_fre_mnth_;
}
inline void CalculatorRequest::_internal_set_fml_mf_fre_mnth(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_mf_fre_mnth_ = value;
}

// int32 FML_INTERVAL = 2;
inline void CalculatorRequest::clear_fml_interval() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_interval_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010U;
}
inline ::int32_t CalculatorRequest::fml_interval() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorRequest.FML_INTERVAL)
  return _internal_fml_interval();
}
inline void CalculatorRequest::set_fml_interval(::int32_t value) {
  _internal_set_fml_interval(value);
  _impl_._has_bits_[0] |= 0x00000010U;
  // @@protoc_insertion_point(field_set:nps.CalculatorRequest.FML_INTERVAL)
}
inline ::int32_t CalculatorRequest::_internal_fml_interval() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_interval_;
}
inline void CalculatorRequest::_internal_set_fml_interval(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_interval_ = value;
}

// int32 FML_FROM_PERIOD = 3;
inline void CalculatorRequest::clear_fml_from_period() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_from_period_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040U;
}
inline ::int32_t CalculatorRequest::fml_from_period() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorRequest.FML_FROM_PERIOD)
  return _internal_fml_from_period();
}
inline void CalculatorRequest::set_fml_from_period(::int32_t value) {
  _internal_set_fml_from_period(value);
  _impl_._has_bits_[0] |= 0x00000040U;
  // @@protoc_insertion_point(field_set:nps.CalculatorRequest.FML_FROM_PERIOD)
}
inline ::int32_t CalculatorRequest::_internal_fml_from_period() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_from_period_;
}
inline void CalculatorRequest::_internal_set_fml_from_period(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_from_period_ = value;
}

// int64 FML_SSSN_ID = 4;
inline void CalculatorRequest::clear_fml_sssn_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_sssn_id_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000020U;
}
inline ::int64_t CalculatorRequest::fml_sssn_id() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorRequest.FML_SSSN_ID)
  return _internal_fml_sssn_id();
}
inline void CalculatorRequest::set_fml_sssn_id(::int64_t value) {
  _internal_set_fml_sssn_id(value);
  _impl_._has_bits_[0] |= 0x00000020U;
  // @@protoc_insertion_point(field_set:nps.CalculatorRequest.FML_SSSN_ID)
}
inline ::int64_t CalculatorRequest::_internal_fml_sssn_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_sssn_id_;
}
inline void CalculatorRequest::_internal_set_fml_sssn_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_sssn_id_ = value;
}

// int32 FML_OTRNSCTN_QTY = 5;
inline void CalculatorRequest::clear_fml_otrnsctn_qty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_otrnsctn_qty_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080U;
}
inline ::int32_t CalculatorRequest::fml_otrnsctn_qty() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorRequest.FML_OTRNSCTN_QTY)
  return _internal_fml_otrnsctn_qty();
}
inline void CalculatorRequest::set_fml_otrnsctn_qty(::int32_t value) {
  _internal_set_fml_otrnsctn_qty(value);
  _impl_._has_bits_[0] |= 0x00000080U;
  // @@protoc_insertion_point(field_set:nps.CalculatorRequest.FML_OTRNSCTN_QTY)
}
inline ::int32_t CalculatorRequest::_internal_fml_otrnsctn_qty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_otrnsctn_qty_;
}
inline void CalculatorRequest::_internal_set_fml_otrnsctn_qty(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_otrnsctn_qty_ = value;
}

// int32 FML_COVER_QTY = 6;
inline void CalculatorRequest::clear_fml_cover_qty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_cover_qty_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100U;
}
inline ::int32_t CalculatorRequest::fml_cover_qty() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorRequest.FML_COVER_QTY)
  return _internal_fml_cover_qty();
}
inline void CalculatorRequest::set_fml_cover_qty(::int32_t value) {
  _internal_set_fml_cover_qty(value);
  _impl_._has_bits_[0] |= 0x00000100U;
  // @@protoc_insertion_point(field_set:nps.CalculatorRequest.FML_COVER_QTY)
}
inline ::int32_t CalculatorRequest::_internal_fml_cover_qty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_cover_qty_;
}
inline void CalculatorRequest::_internal_set_fml_cover_qty(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_cover_qty_ = value;
}

// int32 FML_IDD_BST_BID_QTY = 7;
inline void CalculatorRequest::clear_fml_idd_bst_bid_qty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_idd_bst_bid_qty_ = 0;
  _impl_._has_bits_[0] &= ~0x00000200U;
}
inline ::int32_t CalculatorRequest::fml_idd_bst_bid_qty() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorRequest.FML_IDD_BST_BID_QTY)
  return _internal_fml_idd_bst_bid_qty();
}
inline void CalculatorRequest::set_fml_idd_bst_bid_qty(::int32_t value) {
  _internal_set_fml_idd_bst_bid_qty(value);
  _impl_._has_bits_[0] |= 0x00000200U;
  // @@protoc_insertion_point(field_set:nps.CalculatorRequest.FML_IDD_BST_BID_QTY)
}
inline ::int32_t CalculatorRequest::_internal_fml_idd_bst_bid_qty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_idd_bst_bid_qty_;
}
inline void CalculatorRequest::_internal_set_fml_idd_bst_bid_qty(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_idd_bst_bid_qty_ = value;
}

// int32 FML_O_STT_DYS = 8;
inline void CalculatorRequest::clear_fml_o_stt_dys() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_o_stt_dys_ = 0;
  _impl_._has_bits_[0] &= ~0x00000400U;
}
inline ::int32_t CalculatorRequest::fml_o_stt_dys() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorRequest.FML_O_STT_DYS)
  return _internal_fml_o_stt_dys();
}
inline void CalculatorRequest::set_fml_o_stt_dys(::int32_t value) {
  _internal_set_fml_o_stt_dys(value);
  _impl_._has_bits_[0] |= 0x00000400U;
  // @@protoc_insertion_point(field_set:nps.CalculatorRequest.FML_O_STT_DYS)
}
inline ::int32_t CalculatorRequest::_internal_fml_o_stt_dys() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_o_stt_dys_;
}
inline void CalculatorRequest::_internal_set_fml_o_stt_dys(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_o_stt_dys_ = value;
}

// string FML_MF_GROWTH_FLG = 9;
inline void CalculatorRequest::clear_fml_mf_growth_flg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_mf_growth_flg_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& CalculatorRequest::fml_mf_growth_flg() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nps.CalculatorRequest.FML_MF_GROWTH_FLG)
  return _internal_fml_mf_growth_flg();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CalculatorRequest::set_fml_mf_growth_flg(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.fml_mf_growth_flg_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nps.CalculatorRequest.FML_MF_GROWTH_FLG)
}
inline ::std::string* PROTOBUF_NONNULL CalculatorRequest::mutable_fml_mf_growth_flg()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_fml_mf_growth_flg();
  // @@protoc_insertion_point(field_mutable:nps.CalculatorRequest.FML_MF_GROWTH_FLG)
  return _s;
}
inline const ::std::string& CalculatorRequest::_internal_fml_mf_growth_flg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_mf_growth_flg_.Get();
}
inline void CalculatorRequest::_internal_set_fml_mf_growth_flg(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.fml_mf_growth_flg_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CalculatorRequest::_internal_mutable_fml_mf_growth_flg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.fml_mf_growth_flg_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CalculatorRequest::release_fml_mf_growth_flg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nps.CalculatorRequest.FML_MF_GROWTH_FLG)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.fml_mf_growth_flg_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.fml_mf_growth_flg_.Set("", GetArena());
  }
  return released;
}
inline void CalculatorRequest::set_allocated_fml_mf_growth_flg(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.fml_mf_growth_flg_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.fml_mf_growth_flg_.IsDefault()) {
    _impl_.fml_mf_growth_flg_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nps.CalculatorRequest.FML_MF_GROWTH_FLG)
}

// string FML_MOD_PLCD_FLG = 10;
inline void CalculatorRequest::clear_fml_mod_plcd_flg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_mod_plcd_flg_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::std::string& CalculatorRequest::fml_mod_plcd_flg() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nps.CalculatorRequest.FML_MOD_PLCD_FLG)
  return _internal_fml_mod_plcd_flg();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CalculatorRequest::set_fml_mod_plcd_flg(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.fml_mod_plcd_flg_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nps.CalculatorRequest.FML_MOD_PLCD_FLG)
}
inline ::std::string* PROTOBUF_NONNULL CalculatorRequest::mutable_fml_mod_plcd_flg()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_fml_mod_plcd_flg();
  // @@protoc_insertion_point(field_mutable:nps.CalculatorRequest.FML_MOD_PLCD_FLG)
  return _s;
}
inline const ::std::string& CalculatorRequest::_internal_fml_mod_plcd_flg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_mod_plcd_flg_.Get();
}
inline void CalculatorRequest::_internal_set_fml_mod_plcd_flg(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.fml_mod_plcd_flg_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CalculatorRequest::_internal_mutable_fml_mod_plcd_flg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  return _impl_.fml_mod_plcd_flg_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CalculatorRequest::release_fml_mod_plcd_flg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nps.CalculatorRequest.FML_MOD_PLCD_FLG)
  if ((_impl_._has_bits_[0] & 0x00000002U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002U;
  auto* released = _impl_.fml_mod_plcd_flg_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.fml_mod_plcd_flg_.Set("", GetArena());
  }
  return released;
}
inline void CalculatorRequest::set_allocated_fml_mod_plcd_flg(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  _impl_.fml_mod_plcd_flg_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.fml_mod_plcd_flg_.IsDefault()) {
    _impl_.fml_mod_plcd_flg_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nps.CalculatorRequest.FML_MOD_PLCD_FLG)
}

// .nps.NormalInput normal = 11;
inline bool CalculatorRequest::has_normal() const {
  return specific_input_case() == kNormal;
}
inline bool CalculatorRequest::_internal_has_normal() const {
  return specific_input_case() == kNormal;
}
inline void CalculatorRequest::set_has_normal() {
  _impl_._oneof_case_[0] = kNormal;
}
inline void CalculatorRequest::clear_normal() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (specific_input_case() == kNormal) {
    if (GetArena() == nullptr) {
      delete _impl_.specific_input_.normal_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.specific_input_.normal_);
    }
    clear_has_specific_input();
  }
}
inline ::nps::NormalInput* PROTOBUF_NULLABLE CalculatorRequest::release_normal() {
  // @@protoc_insertion_point(field_release:nps.CalculatorRequest.normal)
  if (specific_input_case() == kNormal) {
    clear_has_specific_input();
    auto* temp = reinterpret_cast<::nps::NormalInput*>(_impl_.specific_input_.normal_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.specific_input_.normal_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::nps::NormalInput& CalculatorRequest::_internal_normal() const {
  return specific_input_case() == kNormal ? *reinterpret_cast<::nps::NormalInput*>(_impl_.specific_input_.normal_) : reinterpret_cast<::nps::NormalInput&>(::nps::_NormalInput_default_instance_);
}
inline const ::nps::NormalInput& CalculatorRequest::normal() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nps.CalculatorRequest.normal)
  return _internal_normal();
}
inline ::nps::NormalInput* PROTOBUF_NULLABLE CalculatorRequest::unsafe_arena_release_normal() {
  // @@protoc_insertion_point(field_unsafe_arena_release:nps.CalculatorRequest.normal)
  if (specific_input_case() == kNormal) {
    clear_has_specific_input();
    auto* temp = reinterpret_cast<::nps::NormalInput*>(_impl_.specific_input_.normal_);
    _impl_.specific_input_.normal_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void CalculatorRequest::unsafe_arena_set_allocated_normal(
    ::nps::NormalInput* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_specific_input();
  if (value) {
    set_has_normal();
    _impl_.specific_input_.normal_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nps.CalculatorRequest.normal)
}
inline ::nps::NormalInput* PROTOBUF_NONNULL CalculatorRequest::_internal_mutable_normal() {
  if (specific_input_case() != kNormal) {
    clear_specific_input();
    set_has_normal();
    _impl_.specific_input_.normal_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::nps::NormalInput>(GetArena()));
  }
  return reinterpret_cast<::nps::NormalInput*>(_impl_.specific_input_.normal_);
}
inline ::nps::NormalInput* PROTOBUF_NONNULL CalculatorRequest::mutable_normal()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::nps::NormalInput* _msg = _internal_mutable_normal();
  // @@protoc_insertion_point(field_mutable:nps.CalculatorRequest.normal)
  return _msg;
}

// .nps.CorpusInput corpus = 12;
inline bool CalculatorRequest::has_corpus() const {
  return specific_input_case() == kCorpus;
}
inline bool CalculatorRequest::_internal_has_corpus() const {
  return specific_input_case() == kCorpus;
}
inline void CalculatorRequest::set_has_corpus() {
  _impl_._oneof_case_[0] = kCorpus;
}
inline void CalculatorRequest::clear_corpus() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (specific_input_case() == kCorpus) {
    if (GetArena() == nullptr) {
      delete _impl_.specific_input_.corpus_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.specific_input_.corpus_);
    }
    clear_has_specific_input();
  }
}
inline ::nps::CorpusInput* PROTOBUF_NULLABLE CalculatorRequest::release_corpus() {
  // @@protoc_insertion_point(field_release:nps.CalculatorRequest.corpus)
  if (specific_input_case() == kCorpus) {
    clear_has_specific_input();
    auto* temp = reinterpret_cast<::nps::CorpusInput*>(_impl_.specific_input_.corpus_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.specific_input_.corpus_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::nps::CorpusInput& CalculatorRequest::_internal_corpus() const {
  return specific_input_case() == kCorpus ? *reinterpret_cast<::nps::CorpusInput*>(_impl_.specific_input_.corpus_) : reinterpret_cast<::nps::CorpusInput&>(::nps::_CorpusInput_default_instance_);
}
inline const ::nps::CorpusInput& CalculatorRequest::corpus() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nps.CalculatorRequest.corpus)
  return _internal_corpus();
}
inline ::nps::CorpusInput* PROTOBUF_NULLABLE CalculatorRequest::unsafe_arena_release_corpus() {
  // @@protoc_insertion_point(field_unsafe_arena_release:nps.CalculatorRequest.corpus)
  if (specific_input_case() == kCorpus) {
    clear_has_specific_input();
    auto* temp = reinterpret_cast<::nps::CorpusInput*>(_impl_.specific_input_.corpus_);
    _impl_.specific_input_.corpus_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void CalculatorRequest::unsafe_arena_set_allocated_corpus(
    ::nps::CorpusInput* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_specific_input();
  if (value) {
    set_has_corpus();
    _impl_.specific_input_.corpus_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nps.CalculatorRequest.corpus)
}
inline ::nps::CorpusInput* PROTOBUF_NONNULL CalculatorRequest::_internal_mutable_corpus() {
  if (specific_input_case() != kCorpus) {
    clear_specific_input();
    set_has_corpus();
    _impl_.specific_input_.corpus_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::nps::CorpusInput>(GetArena()));
  }
  return reinterpret_cast<::nps::CorpusInput*>(_impl_.specific_input_.corpus_);
}
inline ::nps::CorpusInput* PROTOBUF_NONNULL CalculatorRequest::mutable_corpus()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::nps::CorpusInput* _msg = _internal_mutable_corpus();
  // @@protoc_insertion_point(field_mutable:nps.CalculatorRequest.corpus)
  return _msg;
}

// .nps.PensionInput pension = 13;
inline bool CalculatorRequest::has_pension() const {
  return specific_input_case() == kPension;
}
inline bool CalculatorRequest::_internal_has_pension() const {
  return specific_input_case() == kPension;
}
inline void CalculatorRequest::set_has_pension() {
  _impl_._oneof_case_[0] = kPension;
}
inline void CalculatorRequest::clear_pension() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (specific_input_case() == kPension) {
    if (GetArena() == nullptr) {
      delete _impl_.specific_input_.pension_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.specific_input_.pension_);
    }
    clear_has_specific_input();
  }
}
inline ::nps::PensionInput* PROTOBUF_NULLABLE CalculatorRequest::release_pension() {
  // @@protoc_insertion_point(field_release:nps.CalculatorRequest.pension)
  if (specific_input_case() == kPension) {
    clear_has_specific_input();
    auto* temp = reinterpret_cast<::nps::PensionInput*>(_impl_.specific_input_.pension_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.specific_input_.pension_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::nps::PensionInput& CalculatorRequest::_internal_pension() const {
  return specific_input_case() == kPension ? *reinterpret_cast<::nps::PensionInput*>(_impl_.specific_input_.pension_) : reinterpret_cast<::nps::PensionInput&>(::nps::_PensionInput_default_instance_);
}
inline const ::nps::PensionInput& CalculatorRequest::pension() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nps.CalculatorRequest.pension)
  return _internal_pension();
}
inline ::nps::PensionInput* PROTOBUF_NULLABLE CalculatorRequest::unsafe_arena_release_pension() {
  // @@protoc_insertion_point(field_unsafe_arena_release:nps.CalculatorRequest.pension)
  if (specific_input_case() == kPension) {
    clear_has_specific_input();
    auto* temp = reinterpret_cast<::nps::PensionInput*>(_impl_.specific_input_.pension_);
    _impl_.specific_input_.pension_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void CalculatorRequest::unsafe_arena_set_allocated_pension(
    ::nps::PensionInput* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_specific_input();
  if (value) {
    set_has_pension();
    _impl_.specific_input_.pension_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nps.CalculatorRequest.pension)
}
inline ::nps::PensionInput* PROTOBUF_NONNULL CalculatorRequest::_internal_mutable_pension() {
  if (specific_input_case() != kPension) {
    clear_specific_input();
    set_has_pension();
    _impl_.specific_input_.pension_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::nps::PensionInput>(GetArena()));
  }
  return reinterpret_cast<::nps::PensionInput*>(_impl_.specific_input_.pension_);
}
inline ::nps::PensionInput* PROTOBUF_NONNULL CalculatorRequest::mutable_pension()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::nps::PensionInput* _msg = _internal_mutable_pension();
  // @@protoc_insertion_point(field_mutable:nps.CalculatorRequest.pension)
  return _msg;
}

// string FML_USR_ID = 14;
inline void CalculatorRequest::clear_fml_usr_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_usr_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline const ::std::string& CalculatorRequest::fml_usr_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nps.CalculatorRequest.FML_USR_ID)
  return _internal_fml_usr_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CalculatorRequest::set_fml_usr_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  _impl_.fml_usr_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nps.CalculatorRequest.FML_USR_ID)
}
inline ::std::string* PROTOBUF_NONNULL CalculatorRequest::mutable_fml_usr_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_fml_usr_id();
  // @@protoc_insertion_point(field_mutable:nps.CalculatorRequest.FML_USR_ID)
  return _s;
}
inline const ::std::string& CalculatorRequest::_internal_fml_usr_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_usr_id_.Get();
}
inline void CalculatorRequest::_internal_set_fml_usr_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  _impl_.fml_usr_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CalculatorRequest::_internal_mutable_fml_usr_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  return _impl_.fml_usr_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CalculatorRequest::release_fml_usr_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nps.CalculatorRequest.FML_USR_ID)
  if ((_impl_._has_bits_[0] & 0x00000004U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004U;
  auto* released = _impl_.fml_usr_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.fml_usr_id_.Set("", GetArena());
  }
  return released;
}
inline void CalculatorRequest::set_allocated_fml_usr_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004U;
  }
  _impl_.fml_usr_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.fml_usr_id_.IsDefault()) {
    _impl_.fml_usr_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nps.CalculatorRequest.FML_USR_ID)
}

inline bool CalculatorRequest::has_specific_input() const {
  return specific_input_case() != SPECIFIC_INPUT_NOT_SET;
}
inline void CalculatorRequest::clear_has_specific_input() {
  _impl_._oneof_case_[0] = SPECIFIC_INPUT_NOT_SET;
}
inline CalculatorRequest::SpecificInputCase CalculatorRequest::specific_input_case() const {
  return CalculatorRequest::SpecificInputCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// CalculatorResponse

// int32 FML_FML_ORD_AMT_BLCKDCOV_STATUS = 1;
inline void CalculatorResponse::clear_fml_fml_ord_amt_blckdcov_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_fml_ord_amt_blckdcov_status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040U;
}
inline ::int32_t CalculatorResponse::fml_fml_ord_amt_blckdcov_status() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorResponse.FML_FML_ORD_AMT_BLCKDCOV_STATUS)
  return _internal_fml_fml_ord_amt_blckdcov_status();
}
inline void CalculatorResponse::set_fml_fml_ord_amt_blckdcov_status(::int32_t value) {
  _internal_set_fml_fml_ord_amt_blckdcov_status(value);
  _impl_._has_bits_[0] |= 0x00000040U;
  // @@protoc_insertion_point(field_set:nps.CalculatorResponse.FML_FML_ORD_AMT_BLCKDCOV_STATUS)
}
inline ::int32_t CalculatorResponse::_internal_fml_fml_ord_amt_blckdcov_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_fml_ord_amt_blckdcov_status_;
}
inline void CalculatorResponse::_internal_set_fml_fml_ord_amt_blckdcov_status(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_fml_ord_amt_blckdcov_status_ = value;
}

// double FML_GMS_AMNT_ALLCTD = 2;
inline void CalculatorResponse::clear_fml_gms_amnt_allctd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_gms_amnt_allctd_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline double CalculatorResponse::fml_gms_amnt_allctd() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorResponse.FML_GMS_AMNT_ALLCTD)
  return _internal_fml_gms_amnt_allctd();
}
inline void CalculatorResponse::set_fml_gms_amnt_allctd(double value) {
  _internal_set_fml_gms_amnt_allctd(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:nps.CalculatorResponse.FML_GMS_AMNT_ALLCTD)
}
inline double CalculatorResponse::_internal_fml_gms_amnt_allctd() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_gms_amnt_allctd_;
}
inline void CalculatorResponse::_internal_set_fml_gms_amnt_allctd(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_gms_amnt_allctd_ = value;
}

// double FML_CASH_BAL = 3;
inline void CalculatorResponse::clear_fml_cash_bal() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_cash_bal_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline double CalculatorResponse::fml_cash_bal() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorResponse.FML_CASH_BAL)
  return _internal_fml_cash_bal();
}
inline void CalculatorResponse::set_fml_cash_bal(double value) {
  _internal_set_fml_cash_bal(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:nps.CalculatorResponse.FML_CASH_BAL)
}
inline double CalculatorResponse::_internal_fml_cash_bal() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_cash_bal_;
}
inline void CalculatorResponse::_internal_set_fml_cash_bal(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_cash_bal_ = value;
}

// double FML_IDD_LST_PRC = 4;
inline void CalculatorResponse::clear_fml_idd_lst_prc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_idd_lst_prc_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline double CalculatorResponse::fml_idd_lst_prc() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorResponse.FML_IDD_LST_PRC)
  return _internal_fml_idd_lst_prc();
}
inline void CalculatorResponse::set_fml_idd_lst_prc(double value) {
  _internal_set_fml_idd_lst_prc(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:nps.CalculatorResponse.FML_IDD_LST_PRC)
}
inline double CalculatorResponse::_internal_fml_idd_lst_prc() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_idd_lst_prc_;
}
inline void CalculatorResponse::_internal_set_fml_idd_lst_prc(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_idd_lst_prc_ = value;
}

// double FML_ORD_AMT_BLCKD = 5;
inline void CalculatorResponse::clear_fml_ord_amt_blckd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_ord_amt_blckd_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008U;
}
inline double CalculatorResponse::fml_ord_amt_blckd() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorResponse.FML_ORD_AMT_BLCKD)
  return _internal_fml_ord_amt_blckd();
}
inline void CalculatorResponse::set_fml_ord_amt_blckd(double value) {
  _internal_set_fml_ord_amt_blckd(value);
  _impl_._has_bits_[0] |= 0x00000008U;
  // @@protoc_insertion_point(field_set:nps.CalculatorResponse.FML_ORD_AMT_BLCKD)
}
inline double CalculatorResponse::_internal_fml_ord_amt_blckd() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_ord_amt_blckd_;
}
inline void CalculatorResponse::_internal_set_fml_ord_amt_blckd(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_ord_amt_blckd_ = value;
}

// double FML_ORD_NET_VL = 6;
inline void CalculatorResponse::clear_fml_ord_net_vl() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_ord_net_vl_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010U;
}
inline double CalculatorResponse::fml_ord_net_vl() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorResponse.FML_ORD_NET_VL)
  return _internal_fml_ord_net_vl();
}
inline void CalculatorResponse::set_fml_ord_net_vl(double value) {
  _internal_set_fml_ord_net_vl(value);
  _impl_._has_bits_[0] |= 0x00000010U;
  // @@protoc_insertion_point(field_set:nps.CalculatorResponse.FML_ORD_NET_VL)
}
inline double CalculatorResponse::_internal_fml_ord_net_vl() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_ord_net_vl_;
}
inline void CalculatorResponse::_internal_set_fml_ord_net_vl(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_ord_net_vl_ = value;
}

// double FML_CSB_NT_BLNCS = 7;
inline void CalculatorResponse::clear_fml_csb_nt_blncs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_csb_nt_blncs_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020U;
}
inline double CalculatorResponse::fml_csb_nt_blncs() const {
  // @@protoc_insertion_point(field_get:nps.CalculatorResponse.FML_CSB_NT_BLNCS)
  return _internal_fml_csb_nt_blncs();
}
inline void CalculatorResponse::set_fml_csb_nt_blncs(double value) {
  _internal_set_fml_csb_nt_blncs(value);
  _impl_._has_bits_[0] |= 0x00000020U;
  // @@protoc_insertion_point(field_set:nps.CalculatorResponse.FML_CSB_NT_BLNCS)
}
inline double CalculatorResponse::_internal_fml_csb_nt_blncs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fml_csb_nt_blncs_;
}
inline void CalculatorResponse::_internal_set_fml_csb_nt_blncs(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fml_csb_nt_blncs_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace nps


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // nps_5fcal_2eproto_2epb_2eh
