// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nps_cal.proto
#ifndef GRPC_nps_5fcal_2eproto__INCLUDED
#define GRPC_nps_5fcal_2eproto__INCLUDED

#include "nps_cal.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace nps {

class NPSCalculatorService final {
 public:
  static constexpr char const* service_full_name() {
    return "nps.NPSCalculatorService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status NpsCalculater(::grpc::ClientContext* context, const ::nps::CalculatorRequest& request, ::nps::CalculatorResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nps::CalculatorResponse>> AsyncNpsCalculater(::grpc::ClientContext* context, const ::nps::CalculatorRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nps::CalculatorResponse>>(AsyncNpsCalculaterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nps::CalculatorResponse>> PrepareAsyncNpsCalculater(::grpc::ClientContext* context, const ::nps::CalculatorRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nps::CalculatorResponse>>(PrepareAsyncNpsCalculaterRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void NpsCalculater(::grpc::ClientContext* context, const ::nps::CalculatorRequest* request, ::nps::CalculatorResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void NpsCalculater(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::nps::CalculatorResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void NpsCalculater(::grpc::ClientContext* context, const ::nps::CalculatorRequest* request, ::nps::CalculatorResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void NpsCalculater(::grpc::ClientContext* context, const ::nps::CalculatorRequest* request, ::nps::CalculatorResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void NpsCalculater(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::nps::CalculatorResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void NpsCalculater(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::nps::CalculatorResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nps::CalculatorResponse>* AsyncNpsCalculaterRaw(::grpc::ClientContext* context, const ::nps::CalculatorRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nps::CalculatorResponse>* PrepareAsyncNpsCalculaterRaw(::grpc::ClientContext* context, const ::nps::CalculatorRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status NpsCalculater(::grpc::ClientContext* context, const ::nps::CalculatorRequest& request, ::nps::CalculatorResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nps::CalculatorResponse>> AsyncNpsCalculater(::grpc::ClientContext* context, const ::nps::CalculatorRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nps::CalculatorResponse>>(AsyncNpsCalculaterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nps::CalculatorResponse>> PrepareAsyncNpsCalculater(::grpc::ClientContext* context, const ::nps::CalculatorRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nps::CalculatorResponse>>(PrepareAsyncNpsCalculaterRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void NpsCalculater(::grpc::ClientContext* context, const ::nps::CalculatorRequest* request, ::nps::CalculatorResponse* response, std::function<void(::grpc::Status)>) override;
      void NpsCalculater(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::nps::CalculatorResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void NpsCalculater(::grpc::ClientContext* context, const ::nps::CalculatorRequest* request, ::nps::CalculatorResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void NpsCalculater(::grpc::ClientContext* context, const ::nps::CalculatorRequest* request, ::nps::CalculatorResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void NpsCalculater(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::nps::CalculatorResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void NpsCalculater(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::nps::CalculatorResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::nps::CalculatorResponse>* AsyncNpsCalculaterRaw(::grpc::ClientContext* context, const ::nps::CalculatorRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nps::CalculatorResponse>* PrepareAsyncNpsCalculaterRaw(::grpc::ClientContext* context, const ::nps::CalculatorRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_NpsCalculater_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status NpsCalculater(::grpc::ServerContext* context, const ::nps::CalculatorRequest* request, ::nps::CalculatorResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_NpsCalculater : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_NpsCalculater() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_NpsCalculater() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NpsCalculater(::grpc::ServerContext* /*context*/, const ::nps::CalculatorRequest* /*request*/, ::nps::CalculatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNpsCalculater(::grpc::ServerContext* context, ::nps::CalculatorRequest* request, ::grpc::ServerAsyncResponseWriter< ::nps::CalculatorResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_NpsCalculater<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_NpsCalculater : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_NpsCalculater() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::nps::CalculatorRequest, ::nps::CalculatorResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::nps::CalculatorRequest* request, ::nps::CalculatorResponse* response) { return this->NpsCalculater(context, request, response); }));}
    void SetMessageAllocatorFor_NpsCalculater(
        ::grpc::experimental::MessageAllocator< ::nps::CalculatorRequest, ::nps::CalculatorResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::nps::CalculatorRequest, ::nps::CalculatorResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_NpsCalculater() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NpsCalculater(::grpc::ServerContext* /*context*/, const ::nps::CalculatorRequest* /*request*/, ::nps::CalculatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* NpsCalculater(
      ::grpc::CallbackServerContext* /*context*/, const ::nps::CalculatorRequest* /*request*/, ::nps::CalculatorResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* NpsCalculater(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::nps::CalculatorRequest* /*request*/, ::nps::CalculatorResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_NpsCalculater<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_NpsCalculater<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_NpsCalculater : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_NpsCalculater() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_NpsCalculater() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NpsCalculater(::grpc::ServerContext* /*context*/, const ::nps::CalculatorRequest* /*request*/, ::nps::CalculatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_NpsCalculater : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_NpsCalculater() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_NpsCalculater() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NpsCalculater(::grpc::ServerContext* /*context*/, const ::nps::CalculatorRequest* /*request*/, ::nps::CalculatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNpsCalculater(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_NpsCalculater : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_NpsCalculater() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->NpsCalculater(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_NpsCalculater() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NpsCalculater(::grpc::ServerContext* /*context*/, const ::nps::CalculatorRequest* /*request*/, ::nps::CalculatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* NpsCalculater(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* NpsCalculater(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_NpsCalculater : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_NpsCalculater() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nps::CalculatorRequest, ::nps::CalculatorResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::nps::CalculatorRequest, ::nps::CalculatorResponse>* streamer) {
                       return this->StreamedNpsCalculater(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_NpsCalculater() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status NpsCalculater(::grpc::ServerContext* /*context*/, const ::nps::CalculatorRequest* /*request*/, ::nps::CalculatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedNpsCalculater(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nps::CalculatorRequest,::nps::CalculatorResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_NpsCalculater<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_NpsCalculater<Service > StreamedService;
};

}  // namespace nps


#endif  // GRPC_nps_5fcal_2eproto__INCLUDED
